In [1]:
#Q1จงเขียน array ที่มีแต่เลข 0 แบบ vector 10 ตัว และ แบบ Matrix 4x4
import numpy as np
print(np.zeros(10))
b=np.zeros([4,4])
b

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [2]:
#2จงเขียน array ที่มีแต่เลข 1 แบบ vector 5 ตัว และ แบบ Matrix 3x3
#done
a=np.ones(5)
print(a)
b=np.ones([3,3])
b

[1. 1. 1. 1. 1.]


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [3]:
#3 #จงเขียน array ที่มีเป็นการ random ตัวเลข 20 ตัว แบบ float ค่าอยู่ในช่วง 10-99 แล้วนำแต่ละเลขยกกำลังสอง

a3=np.random.rand(10,100,20)
#print(a3)
result3=a3**2
result3

array([[[2.11141891e-01, 8.69942267e-03, 2.17291109e-02, ...,
         2.80672578e-01, 4.63572921e-02, 1.11843519e-02],
        [9.88978602e-01, 4.40685089e-01, 3.16405926e-01, ...,
         1.92691914e-01, 2.48306969e-01, 1.23645444e-01],
        [4.40822827e-01, 1.36734764e-01, 2.03460816e-02, ...,
         4.27245763e-01, 6.79313594e-03, 8.19509483e-02],
        ...,
        [6.34000725e-01, 7.91918253e-02, 1.85668628e-01, ...,
         3.76918111e-02, 3.32974423e-01, 6.28294107e-02],
        [3.34979640e-01, 6.55411486e-01, 6.87845305e-02, ...,
         2.50567078e-01, 8.78168719e-01, 7.73948565e-01],
        [8.84363373e-01, 9.67645367e-02, 6.35678437e-01, ...,
         2.35517903e-02, 8.14476167e-02, 7.25544675e-01]],

       [[1.77461919e-01, 9.61602154e-01, 1.56384962e-01, ...,
         6.21786442e-02, 3.15245504e-01, 6.80734043e-01],
        [6.35655972e-01, 3.68646682e-01, 1.63233480e-02, ...,
         4.33382618e-01, 9.82534794e-01, 8.39870150e-01],
        [1.45631287e-01, 

In [4]:
#4 done ทำเหมือนข้อ 3 แต่เขียนแบบ List comprehension
a4=np.random.rand(10,100,20)
print(a4)
result4=[i**2 for i in a4]
print(result4)

[[[0.39663608 0.08660387 0.67036144 ... 0.78804391 0.95318804 0.12818326]
  [0.96569577 0.33766703 0.54189792 ... 0.26167604 0.07352362 0.28792561]
  [0.32841872 0.1041692  0.78978324 ... 0.0641343  0.23974271 0.51011195]
  ...
  [0.43591501 0.99331277 0.40917297 ... 0.00332159 0.41811298 0.92427695]
  [0.52195621 0.76805458 0.30125887 ... 0.34094523 0.89149709 0.27290921]
  [0.86144027 0.24910093 0.32089655 ... 0.27615785 0.74212668 0.21181408]]

 [[0.92857496 0.42062642 0.16747467 ... 0.55063604 0.55286416 0.26799687]
  [0.64665161 0.98245148 0.66503771 ... 0.88944009 0.94956303 0.83158235]
  [0.20283783 0.51009997 0.90442262 ... 0.37370686 0.4462824  0.20729048]
  ...
  [0.43817021 0.28237486 0.39602061 ... 0.18285905 0.92234972 0.33412023]
  [0.56061611 0.5459345  0.81803949 ... 0.16220622 0.5093122  0.37407107]
  [0.57325864 0.36189825 0.47953761 ... 0.50163959 0.12267456 0.92830536]]

 [[0.80100173 0.26291021 0.94299075 ... 0.88753663 0.27882629 0.88477893]
  [0.25218253 0.585411

In [9]:
#5 done
#51  นำข้อ 3 และ 4 มาเปรียบเวลากัน โดยใช้ฟังก์ชั่น time.time( ) เพื่อจับเวลา แสดงผลลัพธ์ในรูปแบบมิลลิวินาที
#time.time() return second
#เปรียบเทียบ ข้อ 3
import time
t31=time.time()
a3=np.random.rand(10,100,20)
result3=a3**2
t32=time.time()
result51=t32-t31
result511=result51*1000 #1 sec = 1000 mil sec
print(result51)
print(result511)

0.0
0.0


In [10]:
#5 เปรียบเทียบข้อ 4

t31=time.time()

a4=np.random.rand(10,100,20)
result4=[i**2 for i in a4]

t32=time.time()
result51=t32-t31
result511=result51*1000
print(result51)
print(result511)


0.0
0.0


In [11]:
#6 done จงเขียน array ที่ใช้ฟังก์ชั่นใน numpy ได้เลข 10 ถึง 1000
np.arange(10,1001)

array([  10,   11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
         21,   22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
         32,   33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
         43,   44,   45,   46,   47,   48,   49,   50,   51,   52,   53,
         54,   55,   56,   57,   58,   59,   60,   61,   62,   63,   64,
         65,   66,   67,   68,   69,   70,   71,   72,   73,   74,   75,
         76,   77,   78,   79,   80,   81,   82,   83,   84,   85,   86,
         87,   88,   89,   90,   91,   92,   93,   94,   95,   96,   97,
         98,   99,  100,  101,  102,  103,  104,  105,  106,  107,  108,
        109,  110,  111,  112,  113,  114,  115,  116,  117,  118,  119,
        120,  121,  122,  123,  124,  125,  126,  127,  128,  129,  130,
        131,  132,  133,  134,  135,  136,  137,  138,  139,  140,  141,
        142,  143,  144,  145,  146,  147,  148,  149,  150,  151,  152,
        153,  154,  155,  156,  157,  158,  159,  1

In [12]:
#7 done จงเขียน array ที่ใช้ฟังก์ชั่นใน numpy ได้เลขคู่ 10 ถึง 2000 
np.arange(10,2001,2)

array([  10,   12,   14,   16,   18,   20,   22,   24,   26,   28,   30,
         32,   34,   36,   38,   40,   42,   44,   46,   48,   50,   52,
         54,   56,   58,   60,   62,   64,   66,   68,   70,   72,   74,
         76,   78,   80,   82,   84,   86,   88,   90,   92,   94,   96,
         98,  100,  102,  104,  106,  108,  110,  112,  114,  116,  118,
        120,  122,  124,  126,  128,  130,  132,  134,  136,  138,  140,
        142,  144,  146,  148,  150,  152,  154,  156,  158,  160,  162,
        164,  166,  168,  170,  172,  174,  176,  178,  180,  182,  184,
        186,  188,  190,  192,  194,  196,  198,  200,  202,  204,  206,
        208,  210,  212,  214,  216,  218,  220,  222,  224,  226,  228,
        230,  232,  234,  236,  238,  240,  242,  244,  246,  248,  250,
        252,  254,  256,  258,  260,  262,  264,  266,  268,  270,  272,
        274,  276,  278,  280,  282,  284,  286,  288,  290,  292,  294,
        296,  298,  300,  302,  304,  306,  308,  3

In [13]:
#8 done จงเขียน array ที่ใช้ฟังก์ชั่นใน numpy ได้เลขคี่ 12 ถึง 900
a8=np.arange(13,901,2)
a8


array([ 13,  15,  17,  19,  21,  23,  25,  27,  29,  31,  33,  35,  37,
        39,  41,  43,  45,  47,  49,  51,  53,  55,  57,  59,  61,  63,
        65,  67,  69,  71,  73,  75,  77,  79,  81,  83,  85,  87,  89,
        91,  93,  95,  97,  99, 101, 103, 105, 107, 109, 111, 113, 115,
       117, 119, 121, 123, 125, 127, 129, 131, 133, 135, 137, 139, 141,
       143, 145, 147, 149, 151, 153, 155, 157, 159, 161, 163, 165, 167,
       169, 171, 173, 175, 177, 179, 181, 183, 185, 187, 189, 191, 193,
       195, 197, 199, 201, 203, 205, 207, 209, 211, 213, 215, 217, 219,
       221, 223, 225, 227, 229, 231, 233, 235, 237, 239, 241, 243, 245,
       247, 249, 251, 253, 255, 257, 259, 261, 263, 265, 267, 269, 271,
       273, 275, 277, 279, 281, 283, 285, 287, 289, 291, 293, 295, 297,
       299, 301, 303, 305, 307, 309, 311, 313, 315, 317, 319, 321, 323,
       325, 327, 329, 331, 333, 335, 337, 339, 341, 343, 345, 347, 349,
       351, 353, 355, 357, 359, 361, 363, 365, 367, 369, 371, 37

In [14]:
#9 done จงสร้าง identity matrix แบบ 4x4
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
#10 done จงหาว่า array ที่มีสมาชิก 100 ตัว เริ่มจาก 5 ถึง 25 มีผลต่างแต่ละตัวเท่ากับเท่าใด
a10=np.linspace(5,25,100)

a10_1=(a10[0])
a10_2=(a10[1])
a10_3=(a10[2])

print(a10_3-a10_2)
print('ผลต่างแต่ละตัวเท่ากับ ',a10_2-a10_1)

0.20202020202020154
ผลต่างแต่ละตัวเท่ากับ  0.20202020202020243


In [18]:
#11 done
#จงเขียนฟังก์ชั่น random ตัวเลขแบบ float ในช่วง 0-1 ขึ้นมา 1 ตัว
import numpy as np
a=np.random.rand(1)
a

array([0.0101096])

In [20]:
#12จงเขียนฟังก์ชั่นที่ random ตัวเลขแบบ int ในช่วง 50-100 โดยให้อยู่ในรูป Matrix 4x4 และ Transpose  
#done
a12=np.random.randint(50,101,16)
a12
b12=a12.reshape(4,4)
print(b12)
print('---------')
print(b12.T)

[[50 73 95 68]
 [92 86 88 68]
 [66 63 67 73]
 [93 92 77 91]]
---------
[[50 92 66 93]
 [73 86 63 92]
 [95 88 67 77]
 [68 68 73 91]]


In [21]:
#17-done
a=np.arange(1,26)
b=a.reshape(5,5)
print('Result Quiz 17')
print(b)

#13 ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกเฉพาะ 8,9,13,14 

print('Result Quiz 13')
print(b[1:3,2:4])

#14. ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกเฉพาะ 18,19,20
print('Result Quiz 14')
print(b[3,2:5])

#15. ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกเฉพาะ 16,17,21,22
print('Result Quiz 15')
print(b[3:5,:2])

#16. ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกทั้งแถว 3
print('Result Quiz 16')
print(b[2])

Result Quiz 17
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Result Quiz 13
[[ 8  9]
 [13 14]]
Result Quiz 14
[18 19 20]
Result Quiz 15
[[16 17]
 [21 22]]
Result Quiz 16
[11 12 13 14 15]


In [23]:
#18-3 จงเขียนโปรแกรมสุ่มเลขจำนวนเต็มในช่วง 10-100 ออกมาอยู่ใน matrix 5x5 
#และใช้ If-else เช็คทีละตัวว่าตัวใดบ้างที่มีค่ามากกว่า 50 และปริ้นออกมา
#
a=np.random.randint(10,101,25)
b=a.reshape(5,5)
print(b)
b[4][4]

lst=np.arange(0,5)
lst
print('result ตัวที่มากกว่า 50')
for x in lst:
    for y in lst:
        if b[x][y] >50:
            print(b[x][y])
        y=y+1
    x=x+1

[[54 58 49 62 93]
 [43 12 54 34 76]
 [17 77 73 95 28]
 [53 66 21 82 33]
 [46 54 64 93 64]]
result ตัวที่มากกว่า 50
54
58
62
93
54
76
77
73
95
53
66
82
54
64
93
64


In [24]:
#19 done จงเขียนโปรแกรมสุ่มเลขจำนวนเต็มในช่วง 10-100 ออกมาอยู่ใน matrix 5x5 และใช้ conditional selection 
#เช็คว่าตัวใดบ้างมีค่า  มากกว่า 40 นำมาใส่ List ที่สร้างใหม่ และปริ้นออกมา
import numpy as np
a=np.random.randint(10,101,25)
#print(a)
#print(type(a))

b=a.reshape(5,5)
print(b)
#print(type(b))
#print(b.shape)
c=b[b>40]
print('New list > 40 ')
print(c)


[[97 74 68 42 21]
 [35 85 46 34 69]
 [51 59 56 19 28]
 [37 64 65 70 20]
 [25 10 40 35 51]]
New list > 40 
[97 74 68 42 85 46 69 51 59 56 64 65 70 51]


In [25]:
#20-5 done
#เขียนโปรแกรมรับค่าจากผู้ใช้ให้ป้อนเลข 9 ตัว แต่ละตัวต้องไม่ซ้ำกันและมีค่าอยู่ในช่วง 10-100 นำเลข 9 ตัวนั้นมาทำเป็น matrix 
# 3x3 และ transport และหาเลขอยู่ตำแหน่งที่ (2,2)

    
chk1=range(10,101)
list1=[]
i1=-1

a1=int(input('Input1='))
while a1 not in chk1:
    a1=int(input('Re-input='))
i1=i1+1
list1.insert(i1,a1)
print(list1)

a2=int(input('Input2='))
while a2 not in chk1 or a2 in list1:
    a2=int(input('Re-input='))
i1=i1+1
list1.insert(i1,a2)
print(list1)

a3=int(input('input3='))
while a3 not in chk1 or a3 in list1:
    a3=int(input('Re-input='))
i1=i1+1
list1.insert(i1,a3)
print(list1)

a4=int(input('input4='))
while a4 not in chk1 or a4 in list1:
    a4=int(input('Re-input='))
i1=i1+1
list1.insert(i1,a4)
print(list1)

a5=int(input('input5='))
while a5 not in chk1 or a5 in list1:
    a5=int(input('Re-input='))
i1=i1+1
list1.insert(i1,a5)
print(list1)

a6=int(input('input6='))
while a6 not in chk1 or a6 in list1:
    a6=int(input('Re-input='))
i1=i1+1
list1.insert(i1,a6)
print(list1)

a7=int(input('input7='))
while a7 not in chk1 or a7 in list1:
    a7=int(input('Re-input='))
i1=i1+1
list1.insert(i1,a7)
print(list1)

a8=int(input('input8='))
while a8 not in chk1 or a8 in list1:
    a8=int(input('Re-input='))
i1=i1+1
list1.insert(i1,a8)
print(list1)

a9=int(input('input9='))
while a9 not in chk1 or a9 in list1:
    a9=int(input('Re-input='))
i1=i1+1
list1.insert(i1,a9)
print(list1)

result20=np.array(list1)
print(result20)
result20_2=result20.reshape(3,3)
print(result20_2)
c=result20_2.T
print('Transpose')
print(c)
print(c[2][2])

Input1=10
[10]
Input2=11
[10, 11]
input3=12
[10, 11, 12]
input4=13
[10, 11, 12, 13]
input5=14
[10, 11, 12, 13, 14]
input6=15
[10, 11, 12, 13, 14, 15]
input7=16
[10, 11, 12, 13, 14, 15, 16]
input8=17
[10, 11, 12, 13, 14, 15, 16, 17]
input9=18
[10, 11, 12, 13, 14, 15, 16, 17, 18]
[10 11 12 13 14 15 16 17 18]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
Transpose
[[10 13 16]
 [11 14 17]
 [12 15 18]]
18
